#ifndef MENU_H
#define MENU_H

#define IDM_1 100
#define IDM_2 101
#define IDM_3 102
#define IDM_4 103

#define IDM_OPTIMIZATION 0
#define IDM_AVERAGE_CUT 1
#define IDM_RATIO_CUT 2
#define IDM_NORMALIZED_CUT 3
#define IDM_KERNIGHAN_LIN 4
#define IDM_FAST_NEWMAN 5
#define IDM_GUIMERA_AMARAL 6
#define IDM_FAST_MODULARITY 20
#define IDM_CM 21
#define IDM_SA 22

#define IDM_HEURISTIC 7
#define IDM_MFC 8
#define IDM_GIRVAN_NEWMAN 9
#define IDM_TYLER 10
#define IDM_RADICCHI 11
#define IDM_HITS 12
#define IDM_WU_HUBERMAN 13
#define IDM_FEC 14
#define IDM_CPM 15
#define IDM_FCM 23

#define IDM_OTHERS 16
#define IDM_INFOMAP 17
#define IDM_WALKTRAP 18
#define IDM_HALL 19

#define IDM_NETWORKS 200
#define IDM_KARATE 201
#define IDM_DOLPHINS 202
#define IDM_FOOTBALL 203
#define IDM_ADJNOUN 204
#define IDM_LESMIS 205
#define IDM_JAZZ 206
#define IDM_GENERATED_NETWORKS 207
#define IDM_MY_NETWORKS 208

#define IDM_RIGHT_BUTTON 50
#define NUM_RIGHT_BUTTON 7
#endif
